- name: Start VM
  hosts: localhost
  gather_facts: false
  vars:
    instance_name: cloud-compute
    user_name: sem-k32
    ssh_key_path: ~/.ssh/node_yc
  tasks:
    - name: Wait for VM to appear in yc
      command: yc compute instance get --name {{ instance_name }} --format json
      register: vm_info
      until: vm_info.stdout | from_json | json_query("status") == "RUNNING"
      retries: 10
      delay: 5
    - name: Extract external IP
      set_fact:
        vm_ip: "{{ vm_info.stdout | from_json | json_query('network_interfaces[0].primary_v4_address.one_to_one_nat.address') }}"
    - name: Add the new host to dynamic inventory
      add_host:
        name: dynamic_vm
        ansible_host: "{{ vm_ip }}"
        ansible_user: "{{ user_name }}"
        ansible_ssh_private_key_file: "{{ ssh_key_path }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

- name: Setup VM
  vars_files:
    - variables.yaml
  hosts: dynamic_vm
  become: true
  tasks:
    - name: Check connection
      ping:
        data: "Hello"
    - name: Configure git
      community.general.git_config:
        ...
    - name: Get latest repo from github
      git:
        repo: "https://github.com/intsystems/n_ode.git"
        dest: "n_ode"
        version: hypothesis
    - name: Copy raw dataset
      synchronize:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        recursive: yes
      loop:
        - src: ../data/A_DeviceMotion_data
          dest: n_ode/data/A_DeviceMotion_data
        - src: ../data/data_subjects_info.csv
          dest: n_ode/data/data_subjects_info.csv
    - name: Add deadsnakes PPA (Ubuntu)
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
    - name: Install Python 3.12 and pip tools
      package:
        name: 
          - python3.12
          - python3-pip
          - python3-venv
        state: present
    - name: Install poetry
      command: curl -sSL https://install.python-poetry.org | python3 -
      register: ps
    - debug: var=ps.stdout_lines
    - name: Add poetry to system PATH in /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: '^PATH='
        line: 'PATH="{{ ansible_env.PATH }}:~/.local/bin"'
        state: present
    - name: Config poetry
      command: poetry config virtualenvs.in-project true
    - name: Setup env via poetry
      command:
        cmd: poetry install
        chdir: n_ode
    - name: configure wandb
      command: 
        cmd: poetry run wandb login
        chdir: n_ode
      environment:
        WANDB_API_KEY: "{{ wandb_api_key }}"
# - name: Stop VM
#   hosts: localhost
#   gather_facts: false
#   vars:
#     instance_name: cloud_compute
#   tasks:
#     - name: Stop VM
#       command: yc compute instance stop --name {{ instance_name }}